const List<String> kGeneralFallbacks = [
  'The stars align in your favor',
  'Trust your intuition',
  'Patience brings clarity',
  'Your path is clear',
  'Embrace the unknown',
  'Energy flows your way',
  'The universe conspires',
  'Stay open to possibilities',
  'Wisdom comes from within',
  'Timing is everything',
  'Faith guides you forward',
  'The answer is near',
  'Listen to your heart',
  'Change brings growth',
  'Trust the journey',
  'Your power is within',
  'The way opens now',
  'Fortune favors the bold',
  'Clarity comes soon',
  'You already know',
];

const List<String> kLoveFallbacks = [
  'Love surrounds you',
  'Open your heart',
  'Connection is near',
  'Trust in love',
  'Romance blooms soon',
  'Your heart knows the way',
  'Passion awakens now',
  'Love finds you ready',
  'The heart sees clearly',
  'Affection comes your way',
  'Intimacy deepens now',
  'Love speaks softly',
  'Your charm attracts',
  'Relationships flourish',
  'Heart energy flows',
  'Love answers your call',
  'Tenderness surrounds you',
  'Romantic energy rises',
  'Love is patient',
  'Your heart is ready',
];

const List<String> kCareerFallbacks = [
  'Success approaches',
  'Your skills shine',
  'Opportunity knocks',
  'Hard work pays off',
  'New horizons await',
  'Professional growth near',
  'Your talents recognized',
  'Career path clears',
  'Ambition serves you well',
  'Work energy flows',
  'Leadership calls to you',
  'Achievement is near',
  'Your value is clear',
  'Progress comes now',
  'Career stars align',
  'Skills meet opportunity',
  'Work brings reward',
  'Professional luck rises',
  'Your effort shows',
  'Career fortune smiles',
];

const List<String> kYesNoFallbacks = [
  'Yes',
  'No',
  'Maybe',
  'Signs point to yes',
  'Unclear ask again',
  'Most likely yes',
  'Better not say now',
  'Cannot predict yet',
  'Ask with focus',
  'The answer is yes',
  'Lean toward yes',
  'Lean toward no',
  'Uncertain path',
  'Clear yes ahead',
  'Clear no ahead',
  'Possibility exists',
  'Probability high',
  'Probability low',
  'Wait and see',
  'Trust your instinct',
];

const List<String> kDailyFallbacks = [
  'Today brings surprises',
  'Stay open to change',
  'Good energy flows',
  'Embrace the moment',
  'Your day looks bright',
  'Morning brings clarity',
  'Afternoon favors action',
  'Evening rests well',
  'Day energy is strong',
  'Fortune smiles today',
  'Challenges become gifts',
  'Joy finds you now',
  'Peace marks your day',
  'Productivity flows',
  'Connections happen now',
  'Day holds potential',
  'Magic in the mundane',
  'Today is yours',
  'Day fortune is good',
  'Evening brings insight',
];
